### ISSUE TITLE
Replace path.py by pathlib

### ISSUE THREAD

**Issue by pradal** [openalea/deploy#49]
Replace all the call of path.py by using the std pathlib functions

**Comment by pradal** [comment]
An error occur with latest version of path (formerly path.py)!

```python
Traceback (most recent call last):
  File "XXX/openalea-components/multisetup.py", line 63, in <module>
    main()
  File "XXX/openalea-components/multisetup.py", line 58, in main
    mysetup = Multisetup(curdir='.', commands=args, packages=dirs)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "XXX/lib/python3.12/site-packages/openalea.deploy-3.1.2-py3.12.egg/openalea/deploy/multisetup.py", line 74, in __init__
    self.curdir = Path(curdir).abspath()
                  ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Path' object has no attribute 'abspath'
```

**Comment by pradal** [comment]
This has been solved
